# Generated by Django 4.0.2 on 2022-02-16 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_products_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='csp',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
