# Generated by Django 4.0.2 on 2022-02-16 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_price_products_csp_products_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
