# Generated by Django 4.0.2 on 2022-02-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='mrp',
            field=models.IntegerField(default=0.0),
        ),
    ]
