# Generated by Django 4.0.2 on 2022-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.IntegerField(default=0)),
                ('razorpay_merchant_key', models.CharField(max_length=50)),
                ('razorpay_amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=50)),
                ('callback_url', models.CharField(max_length=50)),
            ],
        ),
    ]
