# Generated by Django 4.0.2 on 2022-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_razorpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay',
            name='razorpay_order_id',
            field=models.CharField(max_length=30),
        ),
    ]
