# Generated by Django 4.0.2 on 2022-02-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_products_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_warranty',
            field=models.BooleanField(default=False),
        ),
    ]
