# Generated by Django 4.0.2 on 2022-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_products_in_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_warranty',
            field=models.IntegerField(default=0),
        ),
    ]
