# Generated by Django 4.0.2 on 2022-02-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_products_in_warranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='short_description',
            new_name='shortdescription',
        ),
    ]
