# Generated by Django 4.0.2 on 2022-02-28 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_short_description_products_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
